### ISSUE TITLE
Error (criu/kerndat.c:1048): Unexpected error from clone3 on OL8.4

### ISSUE THREAD

**Issue by dineshputchala** [oracle/linux-uek#12]
Description: /sbin/criu check is failing with "Error (criu/kerndat.c:1048): Unexpected error from clone3" on OracleLinux8.4

bash-4.4# /sbin/criu check --version
Version: 3.15
GitID: f9533f0

bash-4.4# /sbin/criu check --all
Error (criu/util.c:631): exited, status=1
Error (criu/util.c:631): exited, status=1
Error (criu/kerndat.c:1048): Unexpected error from clone3
: Invalid argument
Error (criu/kerndat.c:1181): kerndat_has_clone3_set_tid failed when initializing kerndat.
Error (criu/crtools.c:213): Could not initialize kernel features detection.
Error (criu/kerndat.c:1048): Unexpected error from clone3
: Invalid argument
Error (criu/kerndat.c:1181): kerndat_has_clone3_set_tid failed when initializing kerndat.
Error (criu/crtools.c:213): Could not initialize kernel features detection.
bash-4.4#

bash-4.4# cat /etc/oracle-release
Oracle Linux Server release 8.4

bash-4.4# uname -r
5.4.17-2102.203.6.el8uek.x86_64

I have opened bug for CRIU - https://github.com/checkpoint-restore/criu/issues/1683

Its been updated in above bug that - An incomplete Backport of clone3 in the Oracle kernel.

Also bug - https://github.com/checkpoint-restore/criu/issues/1592 is updated  with below notes:

Originally I was a bit confused, actually the problem is in Oracle UEK v5.4 based kernel. 
Due to commit oracle/linux-uek@d5f2322 which effectively breaks clone3 compatibility checks in kernel. 
CRIU can't detect set_tid support right. So it's Oracle UEK v5.4 which should be fixed.

**Comment by dineshputchala** [comment]
As per CRIU team , its issue in  Oracle UEK v5.4 .

Can you please check ?

**Comment by tvierling** [comment]
I'm sorry this issue report was overlooked. Can you please check whether this is still an issue for you in up-to-date OL8? If so, please reopen the issue with context, and include a `sosreport` of your system to capture configuration data.
