### ISSUE TITLE
Most recent kernel update breaks intel wifi driver

### ISSUE THREAD

**Issue by jamesdedon** [oracle/linux-uek#17]
Lost wifi on Dell XPS 13 laptop after installing latest kernel on OL 9.2. 

Offending kernel version: _vmlinuz-5.15.0-200.131.27.el9uek.x86_64_

Broken network adapter: 
  _*-network                
       description: Wireless interface
       product: Wireless-AC 9260
       vendor: Intel Corporation
       physical id: 0
       bus info: pci@0000:3a:00.0
       logical name: wlp58s0
       version: 29
       serial: 34:13:e8:99:2b:c2
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress msix bus_master cap_list ethernet physical wireless
       configuration: broadcast=yes driver=iwlwifi driverversion=5.15.0-106.131.4.el9uek.x86_64 firmware=46.ff18e32a.0 9260-th-b0-jf-b0- ip= latency=0 link=yes multicast=yes wireless=IEEE 802.11
       resources: irq:16 memory:dc200000-dc203fff_

Reverting to previous kernel fixed issue.

**Comment by tvierling** [comment]
We're looking into this now.

**Comment by schonma** [comment]
i can confirm that
Linux 5.15.0-200.131.27.el9uek.x86_64 #2 SMP Wed Oct 4 22:09:54 PDT 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tvierling** [comment]
Please try the latest update, 5.15.0-201.135.6. We believe this fixed the issue (verified on Dell-branded laptops inside the company).

**Comment by schonma** [comment]
confirmed !
I did a dnf up to Linux  5.15.0-201.135.6.el9uek.x86_64 #2 SMP Thu Nov 30 16:13:06 PST 2023 x86_64 x86_64 x86_64 GNU/Linux ;  **sys64738** and the DELL branded laptop with Intel Corporation Wireless 8265 / 8275 (rev 78) came up with working wifi again
Thank you :)

**Comment by tvierling** [comment]
Thanks, we'll close this issue. (And I appreciate the `sys64738` comment, heh)
