### ISSUE TITLE
wi-fi adapter missing after update

### ISSUE THREAD

**Issue by boboshaq** [oracle/linux-uek#22]
Hi,
After last system update, my wi-fi adapter is missing.
nmtui in radio option tells me: wi-fi hardware: Missing Software: enabled.
When I load previours kernel on system start, wi-fi is present in the system. Also when I start Windows on this machine wi-fi is present on it.

System: Oracle Linux Server release 9.3

lspci:
```
Network controller: Intel Corporation Cannon Point-LP CNVi [Wireless-AC] (rev 30)
Ethernet controller: Intel Corporation Ethernet Connection (6) I219-LM (rev 30)
```
lshw -C network
```
  *-network:0 UNCLAIMED     
       description: Network controller
       product: Cannon Point-LP CNVi [Wireless-AC]
       vendor: Intel Corporation
       physical id: 14.3
       bus info: pci@0000:00:14.3
       version: 30
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress msix cap_list
       configuration: latency=0
       resources: memory:cc33c000-cc33ffff
```
kernels:
```
vmlinuz-5.14.0-284.30.0.1.el9_2.x86_64
vmlinuz-5.14.0-284.30.1.el9_2.x86_64
vmlinuz-5.15.0-106.131.4.el9uek.x86_64
vmlinuz-5.15.0-200.131.27.el9uek.x86_64
vmlinuz-5.14.0-362.8.1.el9_3.x86_64
vmlinuz-5.15.0-200.131.27.1.el9uek.x86_64
```
lspci -nn | grep -i net
```
00:14.3 Network controller [0280]: Intel Corporation Cannon Point-LP CNVi [Wireless-AC] [8086:9df0] (rev 30)
00:1f.6 Ethernet controller [0200]: Intel Corporation Ethernet Connection (6) I219-LM [8086:15bd] (rev 30)
```
grep -i 8086 /lib/modules/$(uname -r)/modules.* | grep -i 9df0
`/lib/modules/5.15.0-200.131.27.1.el9uek.x86_64/modules.alias:alias pci:v00008086d00009DF0sv*sd*bc*sc*i* iwlwifi`

grep -i 8086 /lib/modules/$(uname -r)/modules.* | grep -i 15bd
`/lib/modules/5.15.0-200.131.27.1.el9uek.x86_64/modules.alias:alias pci:v00008086d000015BDsv*sd*bc*sc*i* e1000e`

sudo modprobe iwlwifi
`modprobe: ERROR: could not insert 'iwlwifi': Invalid argument`

**Comment by seeda** [comment]
Can you please try new kernel 5.15.0-201.135.6 and see if it still has the problem. If it does, can you please 
1. upload /var/log/messages file after you did 'sudo modprobe iwlwifi'
2. previous kernel that worked fine

**Comment by YoderExMachina** [comment]
This is a duplicate of issue #17 and is confirmed fixed in that issue.

**Comment by boboshaq** [comment]
Hi,
The problem does not occur in the vmlinuz-5.15.0-201.135.6 kernel.
Thank you!
