### ISSUE TITLE
MADV_DOEXEC and MADV_DONTEXEC should be redefined within a separate numerical range

### ISSUE THREAD

**Issue by cnqpzhang** [oracle/linux-uek#23]
**Description:**

MADV_DOEXEC and MADV_DONTEXEC should be redefined within a separate numerical range otherwise break binary compatibility with mainline kernels.

**Diagnostic Info:**

Kernel v5.4 build from [uek6/u3](https://github.com/oracle/linux-uek/tree/uek6/u3) has a commit https://github.com/oracle/linux-uek/commit/a91ae4fa327d8957e2f806420b8b835269b85bd4, which had two madvise mode numbers defined as below:
```
#define MADV_DOEXEC	22		/* do inherit across exec */
#define MADV_DONTEXEC	23		/* don't inherit across exec */
```
In comparison, Linux mainline v5.4 does not have such definitions, the top number was 21, see [v5.4 219d54332](https://github.com/torvalds/linux/blob/219d54332a09e8d8741c1e1982f5eae56099de85/include/uapi/asm-generic/mman-common.h#L67)

Moving forward, Linux mainline started to use number 22 and 23, at its [5.14-rc1](https://github.com/torvalds/linux/releases/tag/v5.14-rc1) timeframe, see https://github.com/torvalds/linux/commit/4ca9b3859dac14bbef0c27d00667bb5b10917adb.
```
#define MADV_POPULATE_READ	22	/* populate (prefault) page tables readable */
#define MADV_POPULATE_WRITE	23	/* populate (prefault) page tables writable */
```
According to Linux [man-pages](https://www.man7.org/linux/man-pages/man2/madvise.2.html), the way to tell whether MADV_POPULATE_WRITE is supported on a testing system is:
> MADV_POPULATE_WRITE (since Linux 5.14) 
> madvise(0, 0, advice) will return zero iff advice is supported by the kernel and can be relied on to probe for support.

As a result, when we do a syscall `madvise(0, 0, 23)` on [UEKR6 v5.4.17](https://yum.oracle.com/repo/OracleLinux/OL8/developer/UEKR6/aarch64/getPackage/kernel-uek-5.4.17-2136.327.2.el8uek.aarch64.rpm) kernel will return 0 which means `supported`, while Linux [v5.4 mainline](https://github.com/torvalds/linux/commit/219d54332a09e8d8741c1e1982f5eae56099de85) returns `-1` that means `not-supported`. The duplicate definition breaks the binary compatibility.

This issue is currently causing a practical failure on OpenJDK. See the ticket [JDK-8324776](https://bugs.openjdk.org/browse/JDK-8324776) and [discussion](https://mail.openjdk.org/pipermail/hotspot-dev/2024-February/085153.html) upon for details.

**Other issue:**

Kernel v5.15 on [uek7/u2](https://github.com/oracle/linux-uek/tree/uek7/u2) has a similar problem. The commit https://github.com/oracle/linux-uek/commit/4693c5d9d799eb4803c5afc781cc60e2b645e398 integrated the defs of 22 and 23 from Linux mainline, while used 24 and 25 for the two customized mode numbers. 
```
#define MADV_POPULATE_READ	22	/* populate (prefault) page tables readable */
#define MADV_POPULATE_WRITE	23	/* populate (prefault) page tables writable */
#define MADV_DOEXEC	24		/* do inherit across exec */
#define MADV_DONTEXEC	25		/* don't inherit across exec */
```
This created another incompatibility against Linux mainline's mode `MADV_DONTNEED_LOCKED` 24 introduced by https://github.com/torvalds/linux/commit/9457056ac426e5ed0671356509c8dcce69f8dee0 since [v5.18-rc1](https://github.com/torvalds/linux/releases/tag/v5.18-rc1), and mode `MADV_COLLAPSE` 25 added by https://github.com/torvalds/linux/commit/7d8faaf155454f8798ec56404faca29a82689c77 since [v6.1-rc1](https://github.com/torvalds/linux/releases/tag/v6.1-rc1). 

See details at [mainline b401b621](https://github.com/torvalds/linux/blob/b401b621758e46812da61fa58a67c3fd8d91de0d/include/uapi/asm-generic/mman-common.h#L75): 
```
#define MADV_POPULATE_READ	22	/* populate (prefault) page tables readable */
#define MADV_POPULATE_WRITE	23	/* populate (prefault) page tables writable */
#define MADV_DONTNEED_LOCKED	24	/* like DONTNEED, but drop locked pages too */
#define MADV_COLLAPSE	25		/* Synchronous hugepage collapse */
```

**Proposed changes:**

Redefine the customized modes `MADV_DOEXEC` and `MADV_DONTEXEC` within a separate numerical range, for example 101, 102. 

As such it can avoid binary compatibility broken issues, UEK6 and UEK7 can also have same definitions of these two modes, and future UEKs do not need to move them to any new numbers, better for maintenance. 

Any other similar or workable solution is also acceptable.

**Comment by YoderExMachina** [comment]
Thanks for reporting this.  I have created an internal ticket to track the issue.

**Comment by almaclang** [comment]
Thanks, Jeff.

**Comment by YoderExMachina** [comment]
This is now be fixed in UEK7U2, UEK6U3, and UEK5U5.
