### ISSUE TITLE
Backport request: brf, fix dev's rx stats

### ISSUE THREAD

**Issue by CharlieR-o-o-t** [oracle/linux-uek#28]
Is it possible to backport this commit to v5.15: 
https://github.com/torvalds/linux/commit/024ee930cb3c9ae49e4266aee89cfde0ebb407e1

This is very important since dev rx stats is not calculated correctly, because it bypass linux network stack with bpf.

**Comment by YoderExMachina** [comment]
Oracle Linux customers, please file your issue at https://support.oracle.com

Thanks for filing an issue with Oracle Linux. 

GitHub Issues is not an official support channel and we don't offer 
product support here. If you're not yet an Oracle Linux customer, 
consider signing up at https://linux.oracle.com. 

Even if you're not a customer, if we can confirm that an issue is a 
bug we will do our best to fix it and to update this issue 
once it has been fixed. We don't guarantee a fix or feedback and
for now, we will close this issue. If you have Oracle Linux support, 
please use support.oracle.com to report issues.
