### ISSUE TITLE
Inconsistent values in cgroup v1 memory.stat: parameters exceed limit and total host memory

### ISSUE THREAD

**Issue by atamanishche** [oracle/linux-uek#30]
## Description
In cgroup v1, some values in `memory.stat` (e.g., `cache`, `rss`, `mapped_file`) occasionally exceed both the configured memory limit (`memory.limit_in_bytes`) and the total physical memory of the host. This behavior has been observed starting with kernel version **5.15.0-300.163.18**. The issue was not present in kernel version **5.15.0-209.161.7.2**.

The behavior affects not only the `cache` parameter but also other non-`total_*` parameters in `memory.stat`, raising concerns about the reliability of memory accounting.

---

## Steps to Reproduce

1. Create a cgroup v1 for memory management:
    ```bash
    mkdir /sys/fs/cgroup/memory/test_group
    echo <LIMIT_IN_BYTES> > /sys/fs/cgroup/memory/test_group/memory.limit_in_bytes
    echo $$ > /sys/fs/cgroup/memory/test_group/tasks
    ```

2. Run a workload that creates memory pressure. For example:
    ```bash
    find / -type f > /dev/null
    ```

3. Monitor the values in `memory.stat` during and after workload execution:
    ```bash
    cat /sys/fs/cgroup/memory/test_group/memory.stat
    ```

---

## Environment Details
- **OS:** Oracle Linux Server 9.4
- **Kernel Version:**
  - Affected: 5.15.0-300.163.18
  - Not affected: 5.15.0-209.161.7.2
- **Cgroup Version:** v1 (`systemd.legacy_systemd_cgroup_controller`, `systemd.unified_cgroup_hierarchy=0`)
- **Configuration Details:**
  - `memory.limit_in_bytes`: [Specify the limit, e.g., 512M]
  - Workload type: Compression of random data in memory

**Comment by YoderExMachina** [comment]
Oracle Linux customers, please file your issue at https://support.oracle.com

Thanks for filing an issue with Oracle Linux. 

GitHub Issues is not an official support channel and we don't offer 
product support here. If you're not yet an Oracle Linux customer, 
consider signing up at https://linux.oracle.com. 

Even if you're not a customer, if we can confirm that an issue is a 
bug we will do our best to fix it and to update this issue 
once it has been fixed. We don't guarantee a fix or feedback and
for now, we will close this issue. If you have Oracle Linux support, 
please use support.oracle.com to report issues.
