### ISSUE TITLE
need to change behaviour of vhci_hcd driver

### ISSUE THREAD

**Issue by Pyr0Texn1c** [oracle/linux-uek#31]
vhci_hcd driver floods systemlog with messages like:
> [ 1576.226847] vhci_hcd: unlink->seqnum 167689
> [ 1576.226850] vhci_hcd: unlink->seqnum 194648
> [ 1576.226852] vhci_hcd: unlink->seqnum 203495
> [ 1576.226856] vhci_hcd: urb->status -104 
>
this behaviour was mentioned and corrected in main linux stream:
[https://github.com/torvalds/linux/pull/841](url)
but still remains in linux-uek.

**Comment by YoderExMachina** [comment]
You don't mention the kernel version you are using.

**Comment by Pyr0Texn1c** [comment]
> You don't mention the kernel version you are using.

`[root@nft-app03 ~]# uname -a
Linux nft-app03.hq.safmar.ru 5.15.0-302.167.6.1.el9uek.x86_64 #2 SMP Thu Nov 21 21:48:29 PST 2024 x86_64 x86_64 x86_64 GNU/Linux
`
